# Generated by Django 2.1.3 on 2018-12-05 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='id_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='profile_picture',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='types',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('educator', 'Educator')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='freelancers.Location'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='skill',
            field=models.ManyToManyField(to='freelancers.Skill'),
        ),
    ]
