# Generated by Django 2.1.3 on 2018-12-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0002_auto_20181205_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
