# Generated by Django 2.1.3 on 2018-12-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0003_auto_20181206_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='recent_works1',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='recent_works2',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='recent_works3',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
