# Generated by Django 2.1.3 on 2018-12-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0004_auto_20181206_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='profile_picture',
            field=models.CharField(max_length=650, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='recent_works1',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='recent_works2',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='recent_works3',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
