# Generated by Django 2.1.3 on 2018-12-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0005_auto_20181206_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='self_desc',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
