# Generated by Django 2.1.3 on 2018-12-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0006_freelancer_self_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='skill',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='expierience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='province',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='recent_review',
            field=models.CharField(max_length=650, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='skill_level',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='recent_works1',
            field=models.CharField(max_length=650, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='recent_works2',
            field=models.CharField(max_length=650, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='recent_works3',
            field=models.CharField(max_length=650, null=True),
        ),
    ]
