# Generated by Django 2.1.3 on 2018-12-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0007_auto_20181207_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='skill',
            field=models.ManyToManyField(to='freelancers.Skill'),
        ),
    ]
